"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
# from os import getcwd
# from pathlib import Path

APP = ['src/app.py']
APP_NAME = "CV Image Tester"
DATA_FILES = []
OPTIONS = {
  # 'bdist_base': str(Path(getcwd()).parent) + '/build',
  # 'dist_dir': str(Path(getcwd()).parent) + '/dist',
  'iconfile': 'app.icns',
  'argv_emulation': True,
  'plist': {
    'CFBundleName': APP_NAME,
    'CFBundleDisplayName': APP_NAME,
    'CFBundleGetInfoString': "CV Image Tester",
    'CFBundleIdentifier': "com.ganda.osx.test",
    'CFBundleVersion': "0.1.0",
    'CFBundleShortVersionString': "0.1.0",
    'NSHumanReadableCopyright': u"For G&A internal use"
  }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
